[project]
name = "irs-telegram-bot"
version = "2.0.0"
description = "Bot IRS Portugal com Groq API (Moonshot AI - Kimi K2)"
requires-python = ">=3.10"
dependencies = [
    "groq>=0.32.0",
    "python-dotenv>=1.0.0",
    "python-telegram-bot>=21.0",
    "requests>=2.31.0",
]
